#include "quickdraw_region_ops.h"
#include <stdlib.h>
#include <string.h>

static void bbox(const QROMask *m,int *t,int *l,int *b,int *r){
    *t=m->height;*l=m->width;*b=*r=0;
    for(int y=0;y<m->height;y++)for(int x=0;x<m->width;x++)if(qro_get(m,y,x)){
        if(y<*t)*t=y;
        if(x<*l)*l=x;
        if(y+1>*b)*b=y+1;
        if(x+1>*r)*r=x+1;
    }
    if(*t==m->height)*t=*l=*b=*r=0;
}
int qro_get(const QROMask *m,int y,int x){return (m->bits[(size_t)y*m->stride+x/8]>>(7-(x&7)))&1;}
void qro_set(QROMask *m,int y,int x,int v){uint8_t *p=&m->bits[(size_t)y*m->stride+x/8],q=(uint8_t)(0x80>>(x&7));*p=v?*p|q:*p&~q;}
void qro_stats_mask(const QROMask*m,QROStats*s){memset(s,0,sizeof*s);int t,l,b,r;bbox(m,&t,&l,&b,&r);s->bbox_area=(uint64_t)(r-l)*(b-t);for(int y=0;y<m->height;y++){int in=0;for(int x=0;x<m->width;x++){int v=qro_get(m,y,x);s->area+=v;if(v&&!in)s->runs++;in=v;}s->active_lines+=in!=0;}for(int y=0;y<=m->height;y++){int previous=0,changed=0;for(int x=0;x<m->width;x++){int v=(y<m->height?qro_get(m,y,x):0)^(y?qro_get(m,y-1,x):0);if(v!=previous){s->transitions++;changed=1;}previous=v;}if(previous)s->transitions++;s->vertical_events+=changed!=0;}}

int qro_b0_build(const QROMask*m,QROB0*r,QROStats*s){memset(r,0,sizeof*r);r->width=m->width;r->height=m->height;r->stride=m->stride;size_t n=(size_t)m->stride*m->height;r->bits=malloc(n);if(!r->bits)return-1;memcpy(r->bits,m->bits,n);if(s){s->storage_bytes=sizeof*r+n;s->allocations=1;}return 0;}
int qro_b1_build(const QROMask*m,QROB1*r,QROStats*s){memset(r,0,sizeof*r);r->width=m->width;r->height=m->height;bbox(m,&r->top,&r->left,&r->bottom,&r->right);size_t n=0;for(int y=0;y<m->height;y++){int p=0;for(int x=0;x<m->width;x++){int v=qro_get(m,y,x);if(v&&!p)n++;p=v;}}r->offsets=calloc((size_t)m->height+1,sizeof* r->offsets);r->runs=n?malloc(n*sizeof*r->runs):NULL;if(!r->offsets||(n&&!r->runs)){qro_b1_free(r);return-1;}size_t k=0;for(int y=0;y<m->height;y++){r->offsets[y]=k;for(int x=0;x<m->width;){while(x<m->width&&!qro_get(m,y,x))x++;int l=x;while(x<m->width&&qro_get(m,y,x))x++;if(l<x)r->runs[k++]=(QRORun){l,x};}}r->offsets[m->height]=k;r->run_count=k;if(s){s->storage_bytes=sizeof*r+((size_t)m->height+1)*sizeof*r->offsets+k*sizeof*r->runs;s->allocations=n?2:1;}return 0;}
int qro_b2_build(const QROMask*m,QROB2*r,QROStats*s){memset(r,0,sizeof*r);r->width=m->width;r->height=m->height;bbox(m,&r->top,&r->left,&r->bottom,&r->right);size_t cap=(size_t)m->height+1;r->events=calloc(cap,sizeof*r->events);if(!r->events)return-1;uint8_t*prev=calloc((size_t)m->stride,1);if(!prev){qro_b2_free(r);return-1;}for(int y=0;y<m->height;y++){int changes=0,last=0;for(int x=0;x<m->width;x++){int v=qro_get(m,y,x)^((prev[x/8]>>(7-(x&7)))&1);if(v!=last){changes++;last=v;}}if(last)changes++;if(changes){QROEvent*e=&r->events[r->event_count++];e->y=y;e->count=changes;e->x=malloc((size_t)changes*sizeof*e->x);if(!e->x){free(prev);qro_b2_free(r);return-1;}int k=0;last=0;for(int x=0;x<m->width;x++){int v=qro_get(m,y,x)^((prev[x/8]>>(7-(x&7)))&1);if(v!=last)e->x[k++]=(int16_t)x,last=v;}if(last)e->x[k++]=(int16_t)m->width;}memcpy(prev,m->bits+(size_t)y*m->stride,(size_t)m->stride);}free(prev);if(s){s->storage_bytes=sizeof*r+sizeof* r->events*r->event_count;s->allocations=1+r->event_count;}return 0;}
void qro_b0_free(QROB0*r){free(r->bits);memset(r,0,sizeof*r);}void qro_b1_free(QROB1*r){free(r->offsets);free(r->runs);memset(r,0,sizeof*r);}void qro_b2_free(QROB2*r){if(r->events)for(size_t i=0;i<r->event_count;i++)free(r->events[i].x);free(r->events);memset(r,0,sizeof*r);}

static int bop(int a,int b,QROp op){switch(op){case QRO_INTERSECT:return a&b;case QRO_UNION:return a|b;case QRO_DIFF:return a&!b;default:return a^b;}}
int qro_b0_op(const QROB0*a,const QROB0*b,QROp op,QROB0*c,QROStats*s){memset(c,0,sizeof*c);c->width=a->width;c->height=a->height;c->stride=a->stride;size_t n=(size_t)c->stride*c->height;c->bits=malloc(n);if(!c->bits)return-1;for(size_t i=0;i<n;i++){uint8_t x=a->bits[i],y=b->bits[i];switch(op){case QRO_INTERSECT:c->bits[i]=x&y;break;case QRO_UNION:c->bits[i]=x|y;break;case QRO_DIFF:c->bits[i]=x&~y;break;default:c->bits[i]=x^y;}}if(s){s->storage_bytes=sizeof*c+n;s->allocations=1;}return 0;}

static int append_run(QRORun**out,size_t*count,size_t*cap,int l,int r){if(l>=r)return 0;if(*count==*cap){size_t n=*cap?*cap*2:16;QRORun*p=realloc(*out,n*sizeof*p);if(!p)return-1;*out=p;*cap=n;}(*out)[(*count)++]=(QRORun){l,r};return 0;}
static int combine_line(const QRORun*a,size_t na,const QRORun*b,size_t nb,int w,QROp op,QRORun**out,size_t*nout){size_t cap=0;*nout=0;size_t i=0,j=0;int sa=0,sb=0,x=0;while(x<w){int nx=w;if(i<na&&(sa? a[i].right:a[i].left)<nx)nx=sa?a[i].right:a[i].left;if(j<nb&&(sb? b[j].right:b[j].left)<nx)nx=sb?b[j].right:b[j].left;if(bop(sa,sb,op)&&append_run(out,nout,&cap,x,nx)){free(*out);*out=NULL;return-1;}x=nx;while(i<na&&((sa?a[i].right:a[i].left)==x)){if(sa)i++;sa=!sa;}while(j<nb&&((sb?b[j].right:b[j].left)==x)){if(sb)j++;sb=!sb;}}return 0;}
int qro_b1_op(const QROB1*a,const QROB1*b,QROp op,QROB1*c,QROStats*s){memset(c,0,sizeof*c);c->width=a->width;c->height=a->height;c->offsets=calloc((size_t)c->height+1,sizeof*c->offsets);if(!c->offsets)return-1;size_t cap=0;for(int y=0;y<c->height;y++){c->offsets[y]=c->run_count;QRORun*out=NULL;size_t n=0;if(combine_line(a->runs+a->offsets[y],a->offsets[y+1]-a->offsets[y],b->runs+b->offsets[y],b->offsets[y+1]-b->offsets[y],c->width,op,&out,&n)){qro_b1_free(c);return-1;}if(n&&c->run_count+n>cap){cap=c->run_count+n;QRORun*p=realloc(c->runs,cap*sizeof*p);if(!p){free(out);qro_b1_free(c);return-1;}c->runs=p;}if(n)memcpy(c->runs+c->run_count,out,n*sizeof*out);free(out);c->run_count+=n;}c->offsets[c->height]=c->run_count;if(s){s->storage_bytes=sizeof*c+((size_t)c->height+1)*sizeof*c->offsets+c->run_count*sizeof*c->runs;s->allocations=2;}return 0;}

static int event_find(const QROB2*r,size_t*idx,int y,uint8_t*scan){while(*idx<r->event_count&&r->events[*idx].y==y){int inside=0,left=0;QROEvent*e=&r->events[*idx];for(int k=0;k<e->count;k++){int x=e->x[k];if(!inside)left=x;else for(int p=left;p<x;p++)scan[p/8]^=(uint8_t)(0x80>>(p&7));inside=!inside;}(*idx)++;}return 0;}
static int append_event(QROB2*r,int y,const uint8_t*prev,const uint8_t*cur){int changes=0,last=0;for(int x=0;x<r->width;x++){int v=((cur[x/8]>>(7-(x&7)))&1)^((prev[x/8]>>(7-(x&7)))&1);if(v!=last){changes++;last=v;}}if(last)changes++;if(!changes)return 0;QROEvent*e=realloc(r->events,(r->event_count+1)*sizeof*e);if(!e)return-1;r->events=e;e=&r->events[r->event_count++];e->y=y;e->count=changes;e->x=malloc((size_t)changes*sizeof*e->x);if(!e->x)return-1;int k=0;last=0;for(int x=0;x<r->width;x++){int v=((cur[x/8]>>(7-(x&7)))&1)^((prev[x/8]>>(7-(x&7)))&1);if(v!=last)e->x[k++]=(int16_t)x,last=v;}if(last)e->x[k++]=(int16_t)r->width;return 0;}
int qro_b2_op(const QROB2*a,const QROB2*b,QROp op,QROB2*c,QROStats*s){memset(c,0,sizeof*c);c->width=a->width;c->height=a->height;size_t bytes=(size_t)(a->width+7)/8;uint8_t*sa=calloc(bytes,1),*sb=calloc(bytes,1),*prev=calloc(bytes,1),*out=calloc(bytes,1);if(!sa||!sb||!prev||!out){free(sa);free(sb);free(prev);free(out);return-1;}size_t ia=0,ib=0;for(int y=0;y<c->height;y++){event_find(a,&ia,y,sa);event_find(b,&ib,y,sb);for(size_t z=0;z<bytes;z++){uint8_t x=sa[z],v=sb[z];out[z]=op==QRO_INTERSECT?x&v:op==QRO_UNION?x|v:op==QRO_DIFF?x&~v:x^v;}if(append_event(c,y,prev,out)){free(sa);free(sb);free(prev);free(out);qro_b2_free(c);return-1;}memcpy(prev,out,bytes);}free(sa);free(sb);free(prev);free(out);if(s){s->storage_bytes=sizeof*c+sizeof* c->events*c->event_count;s->temporary_bytes=bytes*4;s->allocations=1+c->event_count;}return 0;}

static void apply_run(const QDBitmap*s,QDRect sr,QDBitmap*d,QDRect dr,int y,int l,int r){if(l>=r)return;QDRect z={y,l,y+1,r},a={sr.top+y-dr.top,sr.left+l-dr.left,sr.top+y-dr.top+1,sr.left+r-dr.left};qd_bitblt_r3(s,a,d,z,NULL);}
int qro_b0_apply(const QROB0*r,const QDBitmap*s,QDRect sr,QDBitmap*d,QDRect dr){for(int y=dr.top;y<dr.bottom;y++){if(y<0||y>=r->height)continue;int x=dr.left;while(x<dr.right){while(x<dr.right&&(x<0||x>=r->width||!qro_get((const QROMask*)r,y,x)))x++;int l=x;while(x<dr.right&&x>=0&&x<r->width&&qro_get((const QROMask*)r,y,x))x++;apply_run(s,sr,d,dr,y,l,x);}}return 0;}
int qro_b1_apply(const QROB1*r,const QDBitmap*s,QDRect sr,QDBitmap*d,QDRect dr){for(int y=dr.top;y<dr.bottom;y++)if(y>=0&&y<r->height)for(size_t i=r->offsets[y];i<r->offsets[y+1];i++){int l=r->runs[i].left>dr.left?r->runs[i].left:dr.left,rr=r->runs[i].right<dr.right?r->runs[i].right:dr.right;if(l<rr)apply_run(s,sr,d,dr,y,l,rr);}return 0;}
int qro_b2_apply(const QROB2*r,const QDBitmap*s,QDRect sr,QDBitmap*d,QDRect dr){size_t bytes=(size_t)(r->width+7)/8;uint8_t*scan=calloc(bytes,1);if(!scan)return-1;size_t i=0;for(int y=0;y<dr.bottom;y++){event_find(r,&i,y,scan);if(y<dr.top||y<0||y>=r->height)continue;int x=dr.left;while(x<dr.right){while(x<dr.right&&!(scan[x/8]>>(7-(x&7))&1))x++;int l=x;while(x<dr.right&&(scan[x/8]>>(7-(x&7))&1))x++;apply_run(s,sr,d,dr,y,l,x);}}free(scan);return 0;}
